[package]
name = "crackdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "crackdb"

[[bin]]
name = "crackdb"

[dependencies]
sqlparser = { version = "0.30.0", features = ["serde", "visitor"]}