#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DataType {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    Int8,
    Int16,
    Int32,
    Int64,
    Float32,
    Float64,
    String,
    Boolean,
    DateTime,
    Unknown,
}

impl DataType {
    pub fn is_integer(&self) -> bool {
        match self {
            DataType::UInt8 => true,
            DataType::UInt16 => true,
            DataType::UInt32 => true,
            DataType::UInt64 => true,
            DataType::Int8 => true,
            DataType::Int16 => true,
            DataType::Int32 => true,
            DataType::Int64 => true,
            DataType::Float32 => false,
            DataType::Float64 => false,
            DataType::String => false,
            DataType::Boolean => false,
            DataType::DateTime => false,
            DataType::Unknown => false,
        }
    }
}

impl From<sqlparser::ast::DataType> for DataType {
    fn from(dt: sqlparser::ast::DataType) -> Self {
        match dt {
            sqlparser::ast::DataType::Character(_) => DataType::Unknown,
            sqlparser::ast::DataType::Char(_) => DataType::Unknown,
            sqlparser::ast::DataType::CharacterVarying(_) => DataType::Unknown,
            sqlparser::ast::DataType::CharVarying(_) => DataType::Unknown,
            sqlparser::ast::DataType::Varchar(_) => DataType::Unknown,
            sqlparser::ast::DataType::Nvarchar(_) => DataType::Unknown,
            sqlparser::ast::DataType::Uuid => DataType::Unknown,
            sqlparser::ast::DataType::CharacterLargeObject(_) => DataType::Unknown,
            sqlparser::ast::DataType::CharLargeObject(_) => DataType::Unknown,
            sqlparser::ast::DataType::Clob(_) => DataType::Unknown,
            sqlparser::ast::DataType::Binary(_) => DataType::Unknown,
            sqlparser::ast::DataType::Varbinary(_) => DataType::Unknown,
            sqlparser::ast::DataType::Blob(_) => DataType::Unknown,
            sqlparser::ast::DataType::Numeric(_) => DataType::Unknown,
            sqlparser::ast::DataType::Decimal(_) => DataType::Unknown,
            sqlparser::ast::DataType::Dec(_) => DataType::Unknown,
            sqlparser::ast::DataType::Float(_) => DataType::Float32,
            sqlparser::ast::DataType::TinyInt(_) => DataType::Int8,
            sqlparser::ast::DataType::UnsignedTinyInt(_) => DataType::UInt8,
            sqlparser::ast::DataType::SmallInt(_) => DataType::Int16,
            sqlparser::ast::DataType::UnsignedSmallInt(_) => DataType::UInt16,
            sqlparser::ast::DataType::MediumInt(_) => DataType::Unknown,
            sqlparser::ast::DataType::UnsignedMediumInt(_) => DataType::Unknown,
            sqlparser::ast::DataType::Int(_) => DataType::Int32,
            sqlparser::ast::DataType::Integer(_) => DataType::Int32,
            sqlparser::ast::DataType::UnsignedInt(_) => DataType::UInt32,
            sqlparser::ast::DataType::UnsignedInteger(_) => DataType::UInt32,
            sqlparser::ast::DataType::BigInt(_) => DataType::Int64,
            sqlparser::ast::DataType::UnsignedBigInt(_) => DataType::UInt64,
            sqlparser::ast::DataType::Real => DataType::Unknown,
            sqlparser::ast::DataType::Double => DataType::Float64,
            sqlparser::ast::DataType::DoublePrecision => DataType::Float64,
            sqlparser::ast::DataType::Boolean => DataType::Boolean,
            sqlparser::ast::DataType::Date => DataType::Unknown,
            sqlparser::ast::DataType::Time(_, _) => DataType::Unknown,
            sqlparser::ast::DataType::Datetime(_) => DataType::DateTime,
            sqlparser::ast::DataType::Timestamp(_, _) => DataType::Unknown,
            sqlparser::ast::DataType::Interval => DataType::Unknown,
            sqlparser::ast::DataType::Regclass => DataType::Unknown,
            sqlparser::ast::DataType::Text => DataType::String,
            sqlparser::ast::DataType::String => DataType::String,
            sqlparser::ast::DataType::Bytea => DataType::Unknown,
            sqlparser::ast::DataType::Custom(_, _) => DataType::Unknown,
            sqlparser::ast::DataType::Array(_) => DataType::Unknown,
            sqlparser::ast::DataType::Enum(_) => DataType::Unknown,
            sqlparser::ast::DataType::Set(_) => DataType::Unknown,
        }
    }
}
